### ISSUE TITLE
yaml file in RBAC section of "Configure dynamic provisioning" has indention errors.

### ISSUE THREAD

**Issue by drawsmcgraw** [pivotal/docs-tap#2496]
Page in question:
https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.5/tap/services-toolkit-how-to-guides-dynamic-provisioning-tanzu-postgresql.html#configure-rbac-7

Attempts at apply this file:

```yaml
# provider-kubernetes-tanzu-postgres-read-writer.rbac.yaml

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
 name: tanzu-postgres-read-writer
 labels:
   services.tanzu.vmware.com/aggregate-to-provider-kubernetes: "true"
rules:
- apiGroups:
 - sql.tanzu.vmware.com
 resources:
 - postgres
 verbs:
 - "*"
 ```
 
 Result in the following error:
 ```
 $ kubectl apply -f provider-kubernetes-tanzu-postgres-read-writer.rbac.yaml
error: error parsing provider-kubernetes-tanzu-postgres-read-writer.rbac.yaml: error converting YAML to JSON: yaml: line 8: did not find expected '-' indicator
```

Looks like it's just the indention under the `rules` section for the two RBAC files.
